### ISSUE TITLE
Repository License

### ISSUE THREAD

**Issue by osowskit** [jdennes/contribution-checker-app#22]
👋 I've forked this repository and was wondering if you've considered adding a license 

/cc @jdennes @izuzak

**Comment by jdennes** [comment]
I thought we added MIT originally, and we did:

https://github.com/jdennes/contribution-checker-app/blob/19d44453aecf7af3e36773affff84babd416a4e1/LICENSE

**Comment by osowskit** [comment]
Apologies. I can't believe I missed this
